version: '3.4'

services:
  a4group1mlmodel:
    image: a4group1mlmodel
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 3300"]
    ports:
      - 3300:3300
      - 5678:5678
    environment:
      - FLASK_APP=app.py
